server:
  port: ${SERVER_PORT:8443}
spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak}
keycloak:
  auth-server-url: http://localhost:8484
  realm: my_realm
  resource: my_client
#  public-client: true
  credentials:
    secret: ynflzcr1ZSw8COS3MDyHeN3TytDJU1xh
#  ssl-required: external
#  bearer-only: true
